#! /usr/bin/env ruby

require 'json'

require './generator'

config_file_name = ARGV[0]
output_file_name = ARGV[1]

if config_file_name.nil? || !File.exists?(config_file_name)
  STDERR.puts 'No configuration file specified!'
  exit
end

config = JSON.parse(File.open(config_file_name).read)

html = Generator.create_schedule(config)

if !output_file_name.nil?
  File.open(output_file_name, 'w+') { |file| file.write(html) }
  STDERR.puts "Output written to #{output_file_name}."
else
  puts html
end
